keycloak:
  auth-server-url: http://localhost:8088
  realm: co-habit
  client:
    registration:
      id: co-habit-confidential
      secret: secret
  use-resource-role-mappings: true

server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/cohabit
    username: cohabit
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    elasticsearch:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  elasticsearch: 
    uris:
      - http://localhost:9200

# Configuration CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
project:
  version: @project.version@

logging:
  level:
    org.springframework.web: DEBUG

elasticsearch:
  enabled: false
