keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8088}
  realm: co-habit
  client:
    registration:
      id: co-habit-confidential
      secret: secret
  use-resource-role-mappings: true

server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cohabit}
    username: cohabit
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  elasticsearch:
    uris:
      - ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}
    connection-timeout: 30s
    socket-timeout: 30s
    max-retry-timeout: 120s
    schema-management:
      auto-create-index: true

elasticsearch:
  enabled: true

# Configuration CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
project:
  version: @project.version@

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.elasticsearch: DEBUG
    org.elasticsearch: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
